# All gpio pin ids follow the GPIO.BCM numbering convention, which uses the
# gpio numbers. For instance the pin with gpio-id 17 has the pin-id 11.

# Define the gpio pins you want to use as either OUTPUT or INPUT. gpio-daemon
# uses this to setup the pins when the daemon starts.
gpio-setup:
    17: OUTPUT  # Thermo Relais
    22: OUTPUT  # Door Opener

# Define your custom commands here.
commands:
    "thermo on": set 17 HIGH
    "thermo off": set 17 LOW

    "door unlock": set 22 HIGH
    "door lock": set 22 LOW
    "turn_left": turn_left
    "turn_right": turn_right
    "forward": forward
    "stop": stop
